// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKlZ3A8Z2jJkxbKfa3rl5GHzfImwrxhdY',
    appId: '1:786838573204:web:abdb3ebb6618ff5f32e481',
    messagingSenderId: '786838573204',
    projectId: 'wewall-98577',
    authDomain: 'wewall-98577.firebaseapp.com',
    storageBucket: 'wewall-98577.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiYEW4LQSrSHVlq--sdLMs6fHktQL6XnI',
    appId: '1:786838573204:android:f56bdec08881743d32e481',
    messagingSenderId: '786838573204',
    projectId: 'wewall-98577',
    storageBucket: 'wewall-98577.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWhuikgrHp4KTjvXqCL9X--jAmYqLy_sM',
    appId: '1:786838573204:ios:6eab49287da44a7d32e481',
    messagingSenderId: '786838573204',
    projectId: 'wewall-98577',
    storageBucket: 'wewall-98577.appspot.com',
    iosBundleId: 'com.example.wewall',
  );
}
